feat: clipboard support
hitlug/mirror-web pull request #32
Opened 2021-06-12 08:46 UTC by jubgjf

Automatically copy configBlock to clipboard.

Signed-off-by: jubgjf <guanjiannan@outlook.com>

2021-06-20 05:50 UTC, woshoxxx approved these changes

2021-08-05 17:31 UTC, billchenchina requested changes

2021-08-05 17:31 UTC, billchenchina commented on src/components/homePage/sideCards/configGeneratorCard.js
> +      navigator.clipboard.writeText(configBlock).then(
```
TypeError: Cannot read property 'writeText' of undefined
ConfigGeneratorCard.handleGenerateConfig
src/components/homePage/sideCards/configGeneratorCard.js:78
  75 | 
  76 | if (configBlock !== undefined) {
  77 |   this.setState({ showConfigBlock: true, configBlock: configBlock });
> 78 |   navigator.clipboard.writeText(configBlock).then(
  79 |^    function() {
  80 |       message.success("复制成功", 1);
  81 |     },
```

2021-08-14 15:05 UTC, billchenchina approved these changes

2021-08-14 15:09 UTC, jubgjf commented on src/components/homePage/sideCards/configGeneratorCard.js
> +      navigator.clipboard.writeText(configBlock).then(
Clipboard API 在不同浏览器似乎有兼容性问题，而且在 HTTP 也不能运行。直接改用 react-copy-to-clipboard 了

2021-08-18 10:36 UTC, billchenchina approved these changes
LGTM, thanks!

2021-08-18 10:36 UTC, merged

2021-08-18 10:42 UTC, billchenchina commented
deployed