feat: Add links to doc page in home
hitlug/mirror-web pull request #36
Opened 2021-08-27 15:48 UTC by piggynl

preview:
![image](https://user-images.githubusercontent.com/86339734/131154112-26f2948f-2095-4883-9e54-6c4052c006a3.png)

2021-09-04 23:34 UTC, jubgjf requested changes
1. `docHome.md` 53 行，中文冒号可以改成 英文冒号 + 空格
2. `menu.json` 里，由于添加了 `name` 在主页添加帮助文档链接，和 `path` 的功能有部分重叠。可以考虑将 `path` 全部删掉，改用 `"/doc/" + name` 的形式。这样 `fetch_mirrors_list` 函数也不必使用 `docMap` 查询

2021-09-04 23:51 UTC, piggynl commented
现在 CTAN 的[镜像](https://mirrors.hit.edu.cn/CTAN/)和[文档](https://mirrors.hit.edu.cn/#/doc/ctan) URL 的大小写不一致，那我把文档的改成大写的？

2021-09-05 00:02 UTC, jubgjf commented
我没太懂😢
![image](https://user-images.githubusercontent.com/51768581/132110749-f5daf3f8-b7ba-4509-9406-ef657517431e.png)
你是指这里的 ctan 是小写吗，这个感觉改不改都可以

2021-09-05 01:02 UTC, piggynl commented
> 你是指这里的 ctan 是小写吗

我的意思是 CTAN 的 `name` 和 `path` 大小写不一致，不能直接把 `path` 改成 `"/doc/" + name`。既然无所谓我就改掉了 😢😢😢

2021-09-05 01:31 UTC, jubgjf commented
把
```json
{
    "key": 0,
    "title": "欢迎来到帮助文档",
    "path": "/doc/docHome"
}
```
的 `"path"` 项改成 `"name": "docHome"` 吧。

这样 `"path"` 以后都不用了，`generateMenuItems` 函数里检查 `menu.path === undefined` 也可以简化

最后更新一下 `docHome.md` 的说明就行

2021-09-05 01:50 UTC, jubgjf commented
没更新完😁
![image](https://user-images.githubusercontent.com/51768581/132112227-ce5cd7a5-5d5f-4e9b-b0df-66e1b28aff83.png)

2021-09-05 01:58 UTC, piggynl commented
痛哭 😭😭😭

2021-09-05 02:07 UTC, jubgjf approved these changes

2021-09-06 11:03 UTC, merged