Doc:Add ubuntu-ports
hitlug/mirror-web pull request #74
Opened 2022-03-24 04:38 UTC by 2096779623

2022-03-29 02:40 UTC, billchenchina requested changes

2022-03-29 02:40 UTC, billchenchina commented on public/static/config.json
> -    "label": "Debian",
Well...what?

2022-03-29 04:13 UTC, 2096779623 commented on public/static/config.json
> -    "label": "Debian",
大意了

2022-03-31 12:14 UTC, billchenchina approved these changes

2022-03-31 12:14 UTC, merged